version: 2

sources:
  - name: conformed
    database: raw
    schema: conformed
    tables:
      - name: datedimension
        identifier: DATEDIMENSION
        columns:
          - name: datekey
            tests:
              - not_null
              - unique

  - name: northwind
    database: raw
    schema: northwind
    tables:
      - name: customers
        identifier: CUSTOMERS
        columns:
          - name: customerid
            tests: [not_null, unique]

      - name: products
        identifier: PRODUCTS
        columns:
          - name: productid
            tests: [not_null, unique]

      - name: suppliers
        identifier: SUPPLIERS
        columns:
          - name: supplierid
            tests: [not_null, unique]

      - name: categories
        identifier: CATEGORIES
        columns:
          - name: categoryid
            tests: [not_null, unique]

      - name: employees
        identifier: EMPLOYEES
        columns:
          - name: employeeid
            tests: [not_null, unique]

      - name: shippers
        identifier: SHIPPERS
        columns:
          - name: shipperid
            tests: [not_null, unique]

      - name: orders
        identifier: ORDERS
        columns:
          - name: orderid
            tests: [not_null, unique]

      - name: order_details
        identifier: ORDER_DETAILS
        tests:
          - dbt_utils.unique_combination_of_columns:
              arguments:
                combination_of_columns: [orderid, productid]
